const STRINGS = {
  ru: {
    PLAY: 'Играть',
    READY: 'Готово',
    MENU: 'Меню',
    RESTART: 'Сброс',
    PAUSE: 'Пауза',
    RESUME: 'Продолжить',
    SETTINGS: 'Настройки',
    SOUND_ON: 'Звук вкл',
    SOUND_OFF: 'Звук выкл',
    ASSEMBLE_IMAGE: 'Соберите изображение',
    START: 'Старт',
    SUCCESS: 'Успех',
    MATCH_FOUND: 'Найдено совпадение!',
    LEVEL_COMPLETE: 'Уровень пройден!',
    LEVEL: 'Уровень',
    NEXT_LEVEL: 'Следующий уровень',
    RESTART_LEVEL: 'Повторить уровень',
    TO_MENU: 'В меню',
    HINT: 'Подсказка',
    HINTS_LEFT: 'Подсказок:',
    NO_HINTS: 'Подсказок нет',
    EASY_PUZZLE: 'Тут уже легко ;)',
    OPEN_THEME: 'Открыть тему',
    WATCH_AD_TO_UNLOCK: 'Посмотрите рекламу, чтобы открыть эту тему',
    WATCH_AD: 'Смотреть рекламу',
    CANCEL: 'Отмена',
    OPEN_FOR: 'Открыть',
    YES: 'Да',
    NO: 'Нет',
    SKIP_LEVEL: 'Пропустить уровень',
    SKIP_FOR_AD: 'Пропустить за рекламу',
    COOLDOWN: 'Кулдаун',
    LEVELS: 'уровней',
    HINTS: 'подсказки за рекламу',
    HINTS_FOR_COINS: 'подсказок',
    COINS: 'Монеты',
    FOR: 'за',
    COOLDOWN_LEVELS: 'Кулдаун:',
    OTHER_GAMES: 'Другие игры',
    SOUNDS: 'Звуки',
    ON: 'Вкл',
    OFF: 'Выкл',
    RATE_GAME: 'Оцените игру',
    RATE_GAME_TEXT: 'Понравилась игра? Оставьте оценку!',
    RATE: 'Оценить',
    NOT_NOW: 'Не сейчас',
    DAILY_REWARDS: 'Ежедневные награды',
    DAY: 'День',
    TODAY: 'Сегодня',
    RATING: 'Рейтинг',
    LEADERBOARD: 'Таблица лидеров',
    YOUR_POSITION: 'Ваша позиция',
    LEVELS_COMPLETED: 'Пройдено уровней',
    LOADING: 'Загрузка...',
    ERROR_LOADING: 'Ошибка загрузки рейтинга',
    DOUBLE_REWARD_FOR_AD: 'Удвоить награду за рекламу',
    RECEIVED_COINS: 'Получено:',
    REWARD_DOUBLED: 'Награда удвоена!',
  },
  en: {
    PLAY: 'Play',
    READY: 'Ready',
    MENU: 'Menu',
    RESTART: 'Restart',
    PAUSE: 'Pause',
    RESUME: 'Resume',
    SETTINGS: 'Settings',
    SOUND_ON: 'Sound On',
    SOUND_OFF: 'Sound Off',
    ASSEMBLE_IMAGE: 'Assemble the image',
    START: 'Start',
    SUCCESS: 'Success',
    MATCH_FOUND: 'Match found!',
    LEVEL_COMPLETE: 'Level Complete!',
    LEVEL: 'Level',
    NEXT_LEVEL: 'Next Level',
    RESTART_LEVEL: 'Restart Level',
    TO_MENU: 'To Menu',
    HINT: 'Hint',
    HINTS_LEFT: 'Hints:',
    NO_HINTS: 'No hints',
    EASY_PUZZLE: 'Already easy ;)',
    OPEN_THEME: 'Open theme',
    WATCH_AD_TO_UNLOCK: 'Watch an ad to unlock this theme',
    WATCH_AD: 'Watch ad',
    CANCEL: 'Cancel',
    OPEN_FOR: 'Open',
    YES: 'Yes',
    NO: 'No',
    SKIP_LEVEL: 'Skip level',
    SKIP_FOR_AD: 'Skip for ad',
    COOLDOWN: 'Cooldown',
    LEVELS: 'levels',
    HINTS: 'hints for ad',
    HINTS_FOR_COINS: 'hints',
    COINS: 'Coins',
    FOR: 'for',
    COOLDOWN_LEVELS: 'Cooldown:',
    OTHER_GAMES: 'Other Games',
    SOUNDS: 'Sounds',
    ON: 'On',
    OFF: 'Off',
    RATE_GAME: 'Rate the game',
    RATE_GAME_TEXT: 'Like the game? Leave a rating!',
    RATE: 'Rate',
    NOT_NOW: 'Not now',
    DAILY_REWARDS: 'Daily Rewards',
    DAY: 'Day',
    TODAY: 'Today',
    RATING: 'Rating',
    LEADERBOARD: 'Leaderboard',
    YOUR_POSITION: 'Your position',
    LEVELS_COMPLETED: 'Levels completed',
    LOADING: 'Loading...',
    ERROR_LOADING: 'Error loading rating',
    DOUBLE_REWARD_FOR_AD: 'Double reward for ad',
    RECEIVED_COINS: 'Received:',
    REWARD_DOUBLED: 'Reward doubled!',
  },
};

let lang = 'ru';

export function setLang(l) {
  lang = STRINGS[l] ? l : 'ru';
}

export function getLang() {
  return lang;
}

export function t(key) {
  return STRINGS[lang]?.[key] ?? key;
}

